version: '3.8'
services:
  brain-tumor-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./static:/app/static
      - ./predictions.db:/app/predictions.db
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
